remote_theme: tomjoht/documentation-theme-jekyll@gh-pages

#enable local builds using remote theme
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

repository: nationofmakers/maker-event-playbook

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: Maker Event Playbook
# this appears on the top navigation bar next to the home button

site_title: Maker Event Playbook
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: Nation of Makers
# this appears in the footer

github_editme_path: nationofmakers/maker-event-playbook/blob/master/
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

feedback_subject_line: Maker Event Playbook

feedback_email: makereventplaybook@nationofmakers.us
# used as a contact email for the Feedback link in the top navigation bar

# feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  events:
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
      sidebar: home_sidebar
      topnav: topnav
  #seo default image
  -
    scope:
      path: ""
    values:
      image: /assets/branding/OSMEP-dark-nom-facebook-link-preview.jpg


# these are defaults used for the frontmatter for these file types


sidebars:
- home_sidebar


exclude:
- README

description: "A guide for producing Maker Events, brought to you by the community of maker event producers within Nation of Makers."
# the description is used in the feed.xml file

theme: jekyll-theme-time-machine

baseurl:

url: https://www.makereventplaybook.org

# set timezone
timezone: America/New_York

#seo
#begin seo
title: Maker Event Playbook
tagline: Learn, Share & Produce Great Maker Events!
description: A guide for producing Maker Events, brought to you by the community of maker event producers within Nation of Makers.
logo: /assets/branding/tm-OSMEP-light-nom-left.jpg

google_analytics: UA-172590594-1
